language: php

php:
  - 5.3

before_script:
    - cp app/config/parameters.yml.test app/config/parameters.yml
    - wget -nc http://getcomposer.org/composer.phar
    - php composer.phar update
    - ./bin/prepare-test-env.sh

script: phpunit -c app/ && php app/console --env=test behat --format progress

branches:
    except:
        - experimental

notifications:
    email:
        - travis@knplabs.com
